Log failed commands
hryz/Dapper.Logging pull request #11
Opened 2020-07-24 08:13 UTC by AndrewP-GH

2020-08-13 14:31 UTC, aurokk commented
@hryz

2020-08-13 16:47 UTC, hryz requested changes
Thank you for a nice Idea! I'll think about the best design regarding my comments and get back to this PR.

2020-08-13 16:47 UTC, hryz commented on src/Dapper.Logging/LoggingHook.cs
> +                _config.LogLevel,
Should it be the `error` level? Writing errors with the same severity as the rest of the messages might be confusing.

2020-08-13 16:47 UTC, hryz commented on src/Dapper.Logging/LoggingHook.cs
> +                _config.ExecuteQueryMessage,
We might also need a separate message template for errors.

2020-08-13 16:47 UTC, hryz commented on src/Dapper.Logging/Hooks/ISqlHooks.cs
> +        void CommandFailed(DbCommand command, T context, object elapsedMs, Exception exception);
Adding a method to an interface is a breaking change.
Should we have an empty body here using the _default interface members_ language feature? Also, using an `object` for elapsedMs seems like an error.

2020-08-13 18:10 UTC, hryz commented on src/Dapper.Logging/Hooks/ISqlHooks.cs
> +        void CommandFailed(DbCommand command, T context, object elapsedMs, Exception exception);
I've completely forgotten that the default interface members require `net standard 2.1` and increasing it is also a breaking change.

2020-08-13 18:23 UTC, hryz commented
@aurokk do you need this functionality?
I see that @AndrewP-GH gave up and forked this repo 20 days ago 😁.
I can spend a few hours reimplementing this functionality in a way that won't break anyone if you need it.

2020-08-14 07:10 UTC, aurokk commented
Hello, @hryz!
Yeah, it's very useful to see logs for failed requests, so it would be nice if you add this functionality :)

2020-08-15 19:58 UTC, hryz commented
OK, I'll do it in a few days (I hope 😉)

2020-08-17 21:46 UTC, hryz commented
The same effect as proposed here is achieved in #12 but without breaking changs.
The updated version is here https://www.nuget.org/packages/Dapper.Logging/0.4.3

2020-08-17 21:46 UTC, closed without merging

2020-08-17 21:48 UTC, hryz commented
@aurokk check out the updated package https://www.nuget.org/packages/Dapper.Logging/0.4.3

2020-08-19 11:35 UTC, aurokk commented
@hryz Thank you, works great! 🔥